In [2]:
import numpy as np

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
np.arange(20,51)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [5]:
np.arange(10,51,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50])

In [8]:
import numpy as np
ar=np.arange(0,6).reshape(2,3)
ar

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.random.rand(1)

array([0.93603113])

In [15]:
np.random.rand(25)

array([0.6663504 , 0.8785159 , 0.89144777, 0.66939281, 0.01478456,
       0.57107993, 0.62113114, 0.73267325, 0.85643248, 0.20775081,
       0.37988366, 0.16869343, 0.94461991, 0.55588723, 0.57283407,
       0.34833228, 0.66466972, 0.52813393, 0.72765953, 0.2239747 ,
       0.3987946 , 0.37216347, 0.99797304, 0.76375183, 0.89393102])

In [16]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [17]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [18]:
ar=np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
ar[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
ar[0:3,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [21]:
ar[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [22]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [24]:
mat[-1]

array([21, 22, 23, 24, 25])

In [25]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
np.sum(mat)

325

In [27]:
np.std(mat)

7.211102550927978

In [28]:
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [29]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,12).reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
ar=np.arange(0,12).reshape(3,2,2)
ar


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [33]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
result=np.random.randint(0,100,20)
result

array([51, 79, 69, 80, 89, 56,  7, 17, 93, 72, 55, 53, 49, 82, 37, 57, 55,
       41, 50, 59])

In [36]:
acs=np.sort(result)
acs

array([ 7, 17, 37, 41, 49, 50, 51, 53, 55, 55, 56, 57, 59, 69, 72, 79, 80,
       82, 89, 93])

In [37]:
np.flip(acs)

array([93, 89, 82, 80, 79, 72, 69, 59, 57, 56, 55, 55, 53, 51, 50, 49, 41,
       37, 17,  7])

In [38]:
mat.dtype

dtype('int32')

In [39]:
ms=result[0:6]

In [42]:
ms[:]=90

In [43]:
result

array([90, 90, 90, 90, 90, 90,  7, 17, 93, 72, 55, 53, 49, 82, 37, 57, 55,
       41, 50, 59])

In [44]:
resultcopy=np.copy(result)

In [45]:
resultcopy[:5]=0

In [46]:
resultcopy

array([ 0,  0,  0,  0,  0, 90,  7, 17, 93, 72, 55, 53, 49, 82, 37, 57, 55,
       41, 50, 59])

In [32]:
result

array([90, 90, 90, 90, 90, 90, 20, 59, 71, 73, 91, 92, 86, 91, 30, 64, 25,
       84, 25, 55])

In [37]:
i=np.eye(5).reshape(25)
i

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [41]:
np.ravel(i)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [48]:
i.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [35]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
np.append(mat,[[11,12,13]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [11, 12, 13]])

In [50]:
np.vstack((mat,[11,13,14]))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [11, 13, 14]])

In [53]:
np.hstack((mat,[[4],[6],[9]]))

array([[0, 1, 2, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [54]:
np.vsplit(mat,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [57]:
np.hsplit(mat,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [60]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])